version: "3"

vars:
  ECOMMERCE_CODE_DIR: ecommerce
  CLIENTS_CODE_DIR: clients

tasks:
  install:
    desc: "Install project"
    silent: true
    cmds:
      - echo "## Installing ASDF plugins..."
      - asdf plugin add java || true
      - asdf plugin add maven || true
      - asdf plugin add quarkus || true
      - echo "✅ Asdf plugins installed successfully"
      - echo ""

      - echo "## Installing ASDF tools..."
      - asdf install
      - echo "✅ Asdf tools installed successfully"
      - echo ""

      - task: build

  build-ecommerce:
    desc: "Build ecommerce project"
    silent: true
    dir: "{{.ECOMMERCE_CODE_DIR}}"
    cmds:
      - echo "## Building ecommerce project..."
      - mvn clean test
      - echo "✅ Project built ecommerce successfully"
      - echo ""

  build-clients:
    desc: "Build clients project"
    silent: true
    dir: "{{.CLIENTS_CODE_DIR}}"
    cmds:
      - echo "## Building clients project..."
      - mvn clean test
      - echo "✅ Project built clients successfully"
      - echo ""

  test-ecommerce:
    desc: "Test ecommerce project"
    silent: true
    dir: "{{.ECOMMERCE_CODE_DIR}}"
    cmds:
      - echo "## Testing ecommerce project..."
      - mvn clean test
      - echo "✅ Project test ecommerce successfully"
      - echo ""

  test-clients:
    desc: "Test clients project"
    silent: true
    dir: "{{.CLIENTS_CODE_DIR}}"
    cmds:
      - echo "## Testing clients project..."
      - mvn clean test
      - echo "✅ Project test clients successfully"
      - echo ""

  start-ecommerce:
    desc: "Start ecommerce project"
    silent: true
    dir: "{{.ECOMMERCE_CODE_DIR}}"
    cmds:
      - mvn clean compile quarkus:dev

  start-clients:
    desc: "Start clients project"
    silent: true
    dir: "{{.CLIENTS_CODE_DIR}}"
    cmds:
      - mvn clean compile quarkus:dev
