quarkus:
  analytics:
    disabled: true

  # Database
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:testdb
    invoices:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:testdb

  hibernate-orm:
    log:
      sql: false
    database:
      generation: drop-and-create
    sql-load-script: products/dev-data.sql

    invoices:
      database:
        generation: drop-and-create
      sql-load-script: invoices/dev-data.sql
