quarkus:
  analytics:
    disabled: true

  http:
    port: 8081

  # Database
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:testdb

  hibernate-orm:
    log:
      sql: false
    database:
      generation: drop-and-create
    sql-load-script: dev-data.sql
